# 网站标题
title: "sun Blog Title"

# 网站描述
description: "A brief description of your blog."

# 网站 URL
url: "https://your-username.github.io"

# 网站的作者信息
author:
  name: "Your Name"
  email: "your-email@example.com"
  twitter_username: "your-twitter-username"  # 可选
  github_username: "your-github-username"   # 可选

# 主题设置
theme: minima

# 插件设置
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 其他自定义设置
# 例如，你可以添加自定义的菜单项、社交链接等
